### PR TITLE
#74 Set up styled components in React app

### PR DESCRIPTION
**Pull request by lucievr**
So the basic implementation is done!

There is a `globalStyles.js` file created with styled components. I copied all the styles across initially – hope that's okay. Just thought it would be easier later when components are created to grab the related styles and paste them into the components, and gradually delete everything that isn't a common style from this file. 

There isn't much content yet to show though you can see the header is already styled as the dev-jot main app 😉 

Related to issue: https://github.com/jrobind/dev-jot/issues/74

### CODE REVIEW

**Comment by jrobind** [comment]
Thanks @lucievr, I'll get round to reviewing this later today

**Comment by lucievr** [comment]
> Thanks @lucievr, I'll get round to reviewing this later today

No worries – take your time @jrobind

**Review by jrobind — APPROVED** [review]
This is great! Thanks for doing this 😄

**Comment by jrobind** [comment]
Thanks @lucievr – merging now 👍

**Comment by lucievr** [comment]
Glad you're pleased with it, @jrobind – happy to help 😄

**Pull request merged**
