### PR TITLE
Prevent homepage scroll #12 

### PR DESCRIPTION
**Pull request by Jwright707**
Made the sign-in page non-scrollable. Added minor CSS changes to achieve this.

### CODE REVIEW

**Comment by jrobind** [comment]
Thanks for the PR. Can you please add `.idea` directory to the `.gitignore` file please. We don't want these files added to the project.

Aside from that, the rest looks great.

**Comment by Jwright707** [comment]
@jrobind just added .idea to .gitignore and I tried removing the .idea folder but for some reason it's not allowing me. Shoud I make a completely different PR?

**Comment by jrobind** [comment]
Creating a fresh PR might make things a little easier. Please bear in mind that It’s also good practice to create a new branch, at the moment this PR is from your master branch. If you're unsure please follow [this guide](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

I'll close this PR for now then and look out for your new one, thanks!

**Comment by Jwright707** [comment]
Sounds good @jrobind. Thank you and I'll create a new PR later today.

**Pull request closed without merging**
