### PR TITLE
updated 404 page 

### PR DESCRIPTION
**Pull request by chhatrapalsinhzala007**

### CODE REVIEW

**Comment by jrobind** [comment]
Thanks @chhatrapalsinhzala007, I'll review this later today!

**Comment by chhatrapalsinhzala007** [comment]
Hyy @jrobind.

No problem and please give suggestions to make it more attractive.

**Comment by jrobind** [comment]
Hey @chhatrapalsinhzala007, can you please create a new branch before raising a pull request. 

If you need some guidance, please follow the process outlined in this article: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

Thanks!

**Comment by chhatrapalsinhzala007** [comment]
Okk @jrobind I will.

**Pull request closed without merging**
