### PR TITLE
Lesson counter alignment changed

### PR DESCRIPTION
**Pull request by medhavibasera**
Changed the font size, as well as provided padding so that all the text and images are aligned.

### CODE REVIEW

**Comment by jrobind** [comment]
Hey @medhavi11, just as a heads up for future PRs. Instead of closing the old PR and deleting the branch it's good practice to make any changes on that branch – no need to delete it. That way we can easily track the PR feedback and conversation :)

**Comment by jrobind** [comment]
Thanks for fixing, looks good!

**Comment by medhavibasera** [comment]
Sure sir, Thank you so much for your guidance !!!!

**Comment by jrobind** [comment]
You're welcome 😃

**Pull request merged**
