### PR TITLE
added jest environment + basic tester

### PR DESCRIPTION
**Pull request by mamadou-diallo**
Fix for #46 
Used jest to setup environment

### CODE REVIEW

**Comment by jrobind** [comment]
Awesome work - thank you! If you could resolve those merge conflicts then I can merge this 😄

**Comment by mamadou-diallo** [comment]
@jrobind my latest commit resolves those issues !

**Comment by jrobind** [comment]
Still getting merge conflicts. Have you fetched the latest upstream changes and merged them into your local branch?

If you try to merge the latest changes into your `add-Testing-Environment` branch you should see the merge conflicts appear.

**Comment by mamadou-diallo** [comment]
@jrobind sorry ! I will get all of that sorted for tomorrow

**Comment by jrobind** [comment]
@mamadou-diallo no problem at all 😄

**Comment by mamadou-diallo** [comment]
@jrobind i think I may need help with this as with your new CI implementation i'm not too sure how to get around this

**Comment by jrobind** [comment]
@mamadou-diallo if you check the last error log it says `1:33:13 AM: npm ERR! JSON.parse Unexpected string in JSON at position 270 while parsing '{` – you are missing a comma after `"test": "jest"` in `package.json`. Once this is fixed, if you're able to fix the merge conflicts this will be ready to go.

Thanks!

**Comment by mamadou-diallo** [comment]
@jrobind I think this solves everything

**Comment by mamadou-diallo** [comment]
> @mamadou-diallo if you check the last error log it says `1:33:13 AM: npm ERR! JSON.parse Unexpected string in JSON at position 270 while parsing '{` – you are missing a comma after `"test": "jest"` in `package.json`. Once this is fixed, if you're able to fix the merge conflicts this will be ready to go.
> 
> Thanks!

Thank you - I didn't initally understand how this worked. 
ironically thanks to prettier fixing all the errors was somewhat easy. 
I think this should solve everything !

**Comment by jrobind** [comment]
Great job persisting with this @mamadou-diallo. Looks good, I'll merge now 😄

**Pull request merged**
