### PR TITLE
beginning to try and flush out the tagging system

### PR DESCRIPTION
**Pull request by MSoup**
Quick fix

**Before:**
Clicking "clear" did not erase selected tags.

**After:**
"Clearing" the canvas now clears the selected tags as well.

### CODE REVIEW

**Review by jrobind — APPROVED** [review]
Good spot! Thanks for the update!

**Comment by jrobind** [comment]
@MSoup looks like there's some merge conflicts. If you can fix these then I'll get your changes merged in 😄

**Review by MSoup — COMMENTED** [review]
sorry, I submitted this without really knowing what I was doing. When looking at the latest codebase, it turns out my version is different than the current, but using git fetch upstream isn't grabbing it, so I'm working on an older copy.

**Review by MSoup — COMMENTED** [review]
This is the change that should properly erase the selected tags upon clear - apologies for the multiple commits.

**Comment by jrobind** [comment]
No worries, thanks for addressing the conflicts 😄

**Pull request merged**
